Repository wait4x/wait4x, pull requests merged in 2022-10, with the labels that each got.

#93 Update README example for PostgreSQL syntax
  README.md
Labels: documentation

#101 Add tzdata package in Docker image, to be able to set timezone
  Dockerfile
Labels: feature

#102 Increase the test coverage
  .github/workflows/ci.yaml
  Dockerfile
  go.mod
  go.sum
  internal/app/wait4x/cmd/http_test.go
  pkg/checker/http/http_test.go
  pkg/checker/tcp/tcp_test.go
  pkg/waiter/waiter_test.go
Labels: enhancement

#104 Update MySQL section of the README
  README.md
Labels: documentation

#106 add .exe file extension for windows builds
  Makefile
Labels: bug

#109 Pass TARGETOS to the Makefile
  Dockerfile
Labels: bug
