Repository wait4x/wait4x, pull requests merged in 2025-03, with the labels that each got.

#380 Redesign README.md
  README.md
Labels: documentation

#381 Improve TCP checker tests
  checker/tcp/tcp_test.go
Labels: enhancement

#187 Support self-signed certificates
  README.md
  checker/http/http.go
  internal/cmd/http.go
Labels: feature

#382 Update dependencies
  .github/workflows/ci.yaml
  Dockerfile
  go.mod
  go.sum
Labels: dependencies

#386 Add Wait4X logo
  README.md
  logo.png
Labels: documentation

#390 Using new Docker image tag "wait4x/wait4x" instead of "atkrad/wait4x"
  .github/workflows/ci.yaml
  README.md
  examples/pkg/README.md
Labels: enhancement
